### PR TITLE
Improve bin

### PR DESCRIPTION
**Pull request by szepeviktor**
I hope there is no need to load 2 autoloaders. The original bin had 2 `if`-s.

This PR introduces a straight-forward and explicit bin.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Are tests failing because we actually need 2 autoloaders??

**Comment by szepeviktor** [comment]
> Are tests failing because we actually need 2 autoloaders??

Could it be that tests fail a year ago?

**Comment by BrianHenryIE** [comment]
@szepeviktor Thanks, that's much nicer.

Yeah, Windows tests have never passed.

I added some code to run the tests first with the classes, and then as the packaged phar.

https://github.com/BrianHenryIE/strauss/blob/53cb03e7cd773fa0d5093c2e511700e1883be1ea/.github/workflows/main.yml#L41-L46

https://github.com/BrianHenryIE/strauss/blob/53cb03e7cd773fa0d5093c2e511700e1883be1ea/tests/Integration/Util/IntegrationTestCase.php#L55-L58

**Comment by szepeviktor** [comment]
Very glad to contribute.

**Comment by szepeviktor** [comment]
All right.
The phar distribution is safer.

**Pull request merged**
