### PR TITLE
Stop changing download link in README

### PR DESCRIPTION
**Pull request by szepeviktor**
@BrianHenryIE 

From https://github.com/BrianHenryIE/strauss/commit/f705785298e39b26b665aa9db0ef8a0ed5e9acd5

### CODE REVIEW

**Comment by szepeviktor** [comment]
https://github.com/BrianHenryIE/strauss/blob/f705785298e39b26b665aa9db0ef8a0ed5e9acd5/.github/workflows/main.yml#L40
This may not be available in a PR.

**Comment by BrianHenryIE** [comment]
I just learned about the "latest" link yesterday. I'm on mobile now, so let me check this later. Seems at first glance to be a better approach.

**Comment by szepeviktor** [comment]
> so let me check this later.

@BrianHenryIE Friendly ping from the future 🙃

**Comment by BrianHenryIE** [comment]
I'm going to leave this open until v1.0.0. I like what you're suggesting but when people put that line in scripts, I want the version fixed for now, so I can make breaking changes and they won't be troubled.

**Comment by BrianHenryIE** [comment]
I thought I had merged this already, made the changes thinking that they'd been undone, then read my last comment here and think maybe I should've left it as it was! Oh well.

**Pull request merged**
